[application]

# For font files to get referenced in CSS files by their original names, without the hash Dioxus appends.
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "Political leaning prediction"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
