name: conventional commits

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

permissions: { }

jobs:
  build:
    name: conventional commits
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: read
      packages: read
      statuses: write
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: conventional commits check
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          allowed-commit-types: "build,chore,ci,docs,feat,fix,hotfix,perf,refactor,revert,style,test"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
